"""Add missing schema drift

Revision ID: 6182d9452b0e
Revises: e4ff23aa56eb
Create Date: 2026-08-29 14:37:01.861385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6182d9452b0e'
down_revision: Union[str, Sequence[str], None] = 'e4ff23aa56eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_checkpoints',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.Column('last_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_keyword_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keywords_name'), 'keywords', ['name'], unique=True)
    op.create_index(op.f('ix_keywords_tmdb_keyword_id'), 'keywords', ['tmdb_keyword_id'], unique=True)
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('train_window', sa.String(length=200), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_person_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('known_for', sa.String(length=100), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_index(op.f('ix_people_tmdb_person_id'), 'people', ['tmdb_person_id'], unique=True)
    op.create_table('movie_cast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=True),
    sa.Column('cast_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'person_id', name='uq_movie_cast_person')
    )
    op.create_index('idx_cast_person', 'movie_cast', ['person_id'], unique=False)
    op.create_index(op.f('ix_movie_cast_movie_id'), 'movie_cast', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_cast_person_id'), 'movie_cast', ['person_id'], unique=False)
    op.create_table('movie_crew',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'person_id', 'job', name='uq_movie_crew_person_job')
    )
    op.create_index('idx_crew_person_job', 'movie_crew', ['person_id', 'job'], unique=False)
    op.create_index(op.f('ix_movie_crew_job'), 'movie_crew', ['job'], unique=False)
    op.create_index(op.f('ix_movie_crew_movie_id'), 'movie_crew', ['movie_id'], unique=False)
    op.create_index(op.f('ix_movie_crew_person_id'), 'movie_crew', ['person_id'], unique=False)
    op.create_table('movie_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'keyword_id', name='uq_movie_keyword')
    )
    op.create_index('idx_movie_keywords_kw', 'movie_keywords', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_movie_keywords_keyword_id'), 'movie_keywords', ['keyword_id'], unique=False)
    op.create_index(op.f('ix_movie_keywords_movie_id'), 'movie_keywords', ['movie_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('raw_query', sa.String(length=500), nullable=False),
    sa.Column('parsed_intent', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('clicked_movie_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clicked_movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('refresh_jti', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_jti')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_movie_keywords_movie_id'), table_name='movie_keywords')
    op.drop_index(op.f('ix_movie_keywords_keyword_id'), table_name='movie_keywords')
    op.drop_index('idx_movie_keywords_kw', table_name='movie_keywords')
    op.drop_table('movie_keywords')
    op.drop_index(op.f('ix_movie_crew_person_id'), table_name='movie_crew')
    op.drop_index(op.f('ix_movie_crew_movie_id'), table_name='movie_crew')
    op.drop_index(op.f('ix_movie_crew_job'), table_name='movie_crew')
    op.drop_index('idx_crew_person_job', table_name='movie_crew')
    op.drop_table('movie_crew')
    op.drop_index(op.f('ix_movie_cast_person_id'), table_name='movie_cast')
    op.drop_index(op.f('ix_movie_cast_movie_id'), table_name='movie_cast')
    op.drop_index('idx_cast_person', table_name='movie_cast')
    op.drop_table('movie_cast')
    op.drop_index(op.f('ix_people_tmdb_person_id'), table_name='people')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_keywords_tmdb_keyword_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_name'), table_name='keywords')
    op.drop_table('keywords')
    op.drop_table('ingestion_checkpoints')
    # ### end Alembic commands ###
