"""initial_v4_schema

Revision ID: e4ff23aa56eb
Revises: 
Create Date: 2026-08-11 19:06:03.754461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ff23aa56eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('imdb_id', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('tagline', sa.Text(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('release_date', sa.String(length=50), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('backdrop_url', sa.String(length=500), nullable=True),
    sa.Column('trailer_key', sa.String(length=200), nullable=True),
    sa.Column('tmdb_rating', sa.Float(), nullable=True),
    sa.Column('tmdb_votes', sa.Integer(), nullable=True),
    sa.Column('popularity_score', sa.Float(), nullable=True),
    sa.Column('imdb_rating', sa.Float(), nullable=True),
    sa.Column('imdb_votes', sa.Integer(), nullable=True),
    sa.Column('rt_rating', sa.String(length=20), nullable=True),
    sa.Column('metacritic', sa.String(length=20), nullable=True),
    sa.Column('awards', sa.Text(), nullable=True),
    sa.Column('omdb_checked_at', sa.DateTime(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('cinema_region', sa.String(length=50), nullable=True),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('cast_members', sa.JSON(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('editorial_collections', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movie_language_pop', 'movies', ['language', 'popularity_score'], unique=False)
    op.create_index('idx_movie_popularity', 'movies', ['popularity_score'], unique=False)
    op.create_index('idx_movie_rating', 'movies', ['tmdb_rating'], unique=False)
    op.create_index('idx_movie_region_pop', 'movies', ['cinema_region', 'popularity_score'], unique=False)
    op.create_index('idx_movie_year_pop', 'movies', ['year', 'popularity_score'], unique=False)
    op.create_index(op.f('ix_movies_cinema_region'), 'movies', ['cinema_region'], unique=False)
    op.create_index(op.f('ix_movies_imdb_id'), 'movies', ['imdb_id'], unique=True)
    op.create_index(op.f('ix_movies_title'), 'movies', ['title'], unique=False)
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    op.create_index(op.f('ix_movies_year'), 'movies', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('pref_genres', sa.JSON(), nullable=True),
    sa.Column('preferences_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('movie_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('availability_type', sa.String(length=20), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id', 'region', 'platform', name='uq_availability_movie_region_platform')
    )
    op.create_index(op.f('ix_movie_availability_movie_id'), 'movie_availability', ['movie_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_rating_user_movie')
    )
    op.create_index(op.f('ix_ratings_movie_id'), 'ratings', ['movie_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=50), nullable=False),
    sa.Column('ranking_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_feedback_movie_id'), 'recommendation_feedback', ['movie_id'], unique=False)
    op.create_index(op.f('ix_recommendation_feedback_user_id'), 'recommendation_feedback', ['user_id'], unique=False)
    op.create_table('recommendation_impressions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('ranking_version', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('shown_at', sa.DateTime(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_impressions_movie_id'), 'recommendation_impressions', ['movie_id'], unique=False)
    op.create_index(op.f('ix_recommendation_impressions_user_id'), 'recommendation_impressions', ['user_id'], unique=False)
    op.create_table('taste_controls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('discovery', sa.Integer(), nullable=False),
    sa.Column('global_taste', sa.Integer(), nullable=False),
    sa.Column('challenge', sa.Integer(), nullable=False),
    sa.Column('pace', sa.Integer(), nullable=False),
    sa.Column('hidden_gems', sa.Integer(), nullable=False),
    sa.Column('diversity_boost', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taste_controls_user_id'), 'taste_controls', ['user_id'], unique=True)
    op.create_table('watch_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('watch_time', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_events_movie_id'), 'watch_events', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watch_events_user_id'), 'watch_events', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_watchlist_user_movie')
    )
    op.create_index(op.f('ix_watchlist_items_movie_id'), 'watchlist_items', ['movie_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_movie_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_watch_events_user_id'), table_name='watch_events')
    op.drop_index(op.f('ix_watch_events_movie_id'), table_name='watch_events')
    op.drop_table('watch_events')
    op.drop_index(op.f('ix_taste_controls_user_id'), table_name='taste_controls')
    op.drop_table('taste_controls')
    op.drop_index(op.f('ix_recommendation_impressions_user_id'), table_name='recommendation_impressions')
    op.drop_index(op.f('ix_recommendation_impressions_movie_id'), table_name='recommendation_impressions')
    op.drop_table('recommendation_impressions')
    op.drop_index(op.f('ix_recommendation_feedback_user_id'), table_name='recommendation_feedback')
    op.drop_index(op.f('ix_recommendation_feedback_movie_id'), table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_movie_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_movie_availability_movie_id'), table_name='movie_availability')
    op.drop_table('movie_availability')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_movies_year'), table_name='movies')
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_title'), table_name='movies')
    op.drop_index(op.f('ix_movies_imdb_id'), table_name='movies')
    op.drop_index(op.f('ix_movies_cinema_region'), table_name='movies')
    op.drop_index('idx_movie_year_pop', table_name='movies')
    op.drop_index('idx_movie_region_pop', table_name='movies')
    op.drop_index('idx_movie_rating', table_name='movies')
    op.drop_index('idx_movie_popularity', table_name='movies')
    op.drop_index('idx_movie_language_pop', table_name='movies')
    op.drop_table('movies')
    # ### end Alembic commands ###
