'use client'

import { useState, useEffect } from 'react'
import { Film, Clock, Star, BarChart3, Brain, CalendarDays } from 'lucide-react'
import TasteDNA from '@/components/TasteDNA'

export default function ProfilePage() {
  const [profile, setProfile] = useState(null)
  const [loading, setLoading] = useState(true)
  const [history, setHistory] = useState<any[]>([])
  const [stats, setStats] = useState({ movies: 0, hours: 0, avgRating: 0, topGenre: 'N/A' })

  useEffect(() => {
    async function fetchData() {
      try {
        const [profileRes, historyRes] = await Promise.all([
          fetch('/api/users/1/profile'),
          fetch('/api/users/1/history'),
        ])
        if (profileRes.ok) {
          const data = await profileRes.json()
          setProfile(data.profile || data)
        }
        if (historyRes.ok) {
          const data = await historyRes.json()
          const h = data.history || data.results || []
          setHistory(h)
          setStats({
            movies: h.length,
            hours: Math.round(h.reduce((a: number, m: any) => a + (m.runtime || 120), 0) / 60),
            avgRating: h.length > 0 ? (h.reduce((a: number, m: any) => a + (m.rating || 0), 0) / h.length) : 0,
            topGenre: 'Action',
          })
        }
      } catch { /* ignore */ }
      setLoading(false)
    }
    fetchData()
  }, [])

  const profileData = profile as any

  return (
    <div className="min-h-screen bg-[var(--bg-primary)]">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="flex items-center gap-4 mb-8">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-500 flex items-center justify-center">
            <Brain className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-semibold text-[var(--text-primary)] display-font">Your Cinematic Fingerprint</h1>
            <p className="text-sm text-[var(--text-secondary)]">Your unique taste profile generated by our neural engine</p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
          {[
            { icon: Film, label: 'Movies Watched', value: stats.movies },
            { icon: Clock, label: 'Total Hours', value: stats.hours },
            { icon: Star, label: 'Avg Rating', value: stats.avgRating.toFixed(1) },
            { icon: BarChart3, label: 'Top Genre', value: stats.topGenre },
          ].map((stat) => (
            <div key={stat.label}
              className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100 hover:shadow-md transition-shadow">
              <div className="flex items-center gap-3 mb-3">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 flex items-center justify-center">
                  <stat.icon className="w-5 h-5 text-indigo-600" />
                </div>
              </div>
              <p className="text-2xl font-semibold text-[var(--text-primary)]">{stat.value}</p>
              <p className="text-xs text-gray-400 mt-1">{stat.label}</p>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
            <h2 className="text-lg font-semibold text-[var(--text-primary)] display-font mb-4">Genre Distribution</h2>
            <TasteDNA profile={profileData} loading={loading} />
          </div>
          <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
            <h2 className="text-lg font-semibold text-[var(--text-primary)] display-font mb-4">Profile Details</h2>
            {profileData ? (
              <div className="space-y-4">
                {profileData.preferred_decades?.length > 0 && (
                  <div>
                    <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Preferred Eras</p>
                    <div className="flex gap-2">
                      {profileData.preferred_decades.map((d: any) => (
                        <span key={d[0] || d} className="px-3 py-1.5 text-xs bg-indigo-50 text-indigo-700 rounded-full">
                          {d[0] || d}s
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {profileData.top_directors?.length > 0 && (
                  <div>
                    <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Favorite Directors</p>
                    <div className="flex flex-wrap gap-2">
                      {profileData.top_directors.map((d: any) => (
                        <span key={d[0] || d} className="px-3 py-1.5 text-xs bg-violet-50 text-violet-700 rounded-full">
                          {d[0] || d}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {profileData.language_preferences?.length > 0 && (
                  <div>
                    <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Languages</p>
                    <div className="flex gap-2">
                      {profileData.language_preferences.map((l: any) => (
                        <span key={l[0] || l} className="px-3 py-1.5 text-xs bg-amber-50 text-amber-700 rounded-full">
                          {l[0] || l}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
                {profileData.avg_runtime_preference && (
                  <div>
                    <p className="text-xs text-gray-400 uppercase tracking-wider mb-2">Preferred Runtime</p>
                    <p className="text-sm text-[var(--text-primary)]">{profileData.avg_runtime_preference} min</p>
                  </div>
                )}
              </div>
            ) : (
              <p className="text-sm text-gray-400">Not enough data yet. Keep watching!</p>
            )}
          </div>
        </div>

        <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
          <div className="flex items-center gap-2 mb-4">
            <CalendarDays className="w-5 h-5 text-indigo-600" />
            <h2 className="text-lg font-semibold text-[var(--text-primary)] display-font">Recent Activity</h2>
          </div>
          {history.length > 0 ? (
            <div className="space-y-3">
              {history.slice(0, 10).map((m: any, i: number) => (
                <div key={i} className="flex items-center gap-3 p-3 rounded-xl hover:bg-gray-50 transition-colors cursor-pointer"
                  onClick={() => { window.location.href = '/movie/' + (m.tmdb_id || m.id) }}>
                  {m.poster_url ? (
                    <img src={m.poster_url} alt="" className="w-10 h-14 rounded-lg object-cover" />
                  ) : (
                    <div className="w-10 h-14 rounded-lg bg-gray-100 flex items-center justify-center">
                      <Film className="w-4 h-4 text-gray-400" />
                    </div>
                  )}
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium text-[var(--text-primary)] truncate">{m.title}</p>
                    <p className="text-xs text-gray-400">{m.genres?.slice(0, 2).join(', ')}{m.rating ? ' \u00b7 ' + m.rating.toFixed(1) : ''}</p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div className="text-center py-10 text-gray-400">
              <Film className="w-8 h-8 mx-auto mb-2 opacity-50" />
              <p className="text-sm">No watch history yet</p>
              <p className="text-xs mt-1">Start watching movies to build your profile</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
