"""
Movie Intelligence Platform — Curated Master Catalog
Pre-populated rich global cinema metadata across industries and genres.
Guarantees immediate offline operation, instant search, mood mapping, and cinema clusters.
"""

from typing import List, Dict, Any

CURATED_CATALOG: List[Dict[str, Any]] = [
    # ── Hollywood & Classics ───────────────────────────────────────────────
    {
        "tmdb_id": 155,
        "imdb_id": "tt0468569",
        "title": "The Dark Knight",
        "overview": "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
        "tagline": "Why So Serious?",
        "genres": ["Action", "Crime", "Drama", "Thriller"],
        "language": "en",
        "release_date": "2008-07-16",
        "year": 2008,
        "runtime": 152,
        "poster_url": "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/hkBaDkMWbLaf8B1rsqPpCYPtqwh.jpg",
        "trailer_key": "EXeTwQWrcwY",
        "tmdb_rating": 8.5,
        "tmdb_votes": 31200,
        "popularity_score": 98.4,
        "director": "Christopher Nolan",
        "cast_members": ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine", "Gary Oldman"],
        "cinema_region": "hollywood",
        "keywords": ["batman", "joker", "crime", "dc comics", "hero"],
        "editorial_collections": ["trending", "top_rated", "intense", "epic"]
    },
    {
        "tmdb_id": 27205,
        "imdb_id": "tt1375666",
        "title": "Inception",
        "overview": "Cobb, a skilled thief who steals corporate secrets through the use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
        "tagline": "Your mind is the scene of the crime.",
        "genres": ["Action", "Science Fiction", "Adventure"],
        "language": "en",
        "release_date": "2010-07-15",
        "year": 2010,
        "runtime": 148,
        "poster_url": "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
        "trailer_key": "YoHD9XEInc0",
        "tmdb_rating": 8.4,
        "tmdb_votes": 35400,
        "popularity_score": 94.2,
        "director": "Christopher Nolan",
        "cast_members": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy", "Ken Watanabe"],
        "cinema_region": "hollywood",
        "keywords": ["dream", "subconscious", "heist", "mind", "reality"],
        "editorial_collections": ["trending", "top_rated", "thoughtful", "epic"]
    },
    {
        "tmdb_id": 238,
        "imdb_id": "tt0068646",
        "title": "The Godfather",
        "overview": "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps up to take care of the would-be killers, launching a campaign of bloody revenge.",
        "tagline": "An offer you can't refuse.",
        "genres": ["Drama", "Crime"],
        "language": "en",
        "release_date": "1972-03-14",
        "year": 1972,
        "runtime": 175,
        "poster_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "sY1S34973zA",
        "tmdb_rating": 8.7,
        "tmdb_votes": 19400,
        "popularity_score": 89.6,
        "director": "Francis Ford Coppola",
        "cast_members": ["Marlon Brando", "Al Pacino", "James Caan", "Robert Duvall", "Diane Keaton"],
        "cinema_region": "hollywood",
        "keywords": ["mafia", "crime family", "patriarch", "revenge", "italy"],
        "editorial_collections": ["top_rated", "thoughtful", "intense"]
    },
    {
        "tmdb_id": 157336,
        "imdb_id": "tt0816692",
        "title": "Interstellar",
        "overview": "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
        "tagline": "Mankind was born on Earth. It was never meant to die here.",
        "genres": ["Adventure", "Drama", "Science Fiction"],
        "language": "en",
        "release_date": "2014-11-05",
        "year": 2014,
        "runtime": 169,
        "poster_url": "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
        "trailer_key": "zSWdZVtXT7E",
        "tmdb_rating": 8.4,
        "tmdb_votes": 33100,
        "popularity_score": 96.0,
        "director": "Christopher Nolan",
        "cast_members": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
        "cinema_region": "hollywood",
        "keywords": ["black hole", "space exploration", "relativity", "wormhole", "time travel"],
        "editorial_collections": ["trending", "top_rated", "thoughtful", "epic"]
    },
    {
        "tmdb_id": 680,
        "imdb_id": "tt0110912",
        "title": "Pulp Fiction",
        "overview": "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
        "tagline": "Just because you are a character doesn't mean you have character.",
        "genres": ["Thriller", "Crime"],
        "language": "en",
        "release_date": "1994-09-10",
        "year": 1994,
        "runtime": 154,
        "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        "trailer_key": "t4LV9Z0XmPQ",
        "tmdb_rating": 8.5,
        "tmdb_votes": 26500,
        "popularity_score": 88.3,
        "director": "Quentin Tarantino",
        "cast_members": ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis", "Ving Rhames"],
        "cinema_region": "hollywood",
        "keywords": ["nonlinear", "hitman", "dialogue", "los angeles", "cult"],
        "editorial_collections": ["top_rated", "intense", "funny"]
    },
    {
        "tmdb_id": 244786,
        "imdb_id": "tt2582802",
        "title": "Whiplash",
        "overview": "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
        "tagline": "The road to greatness can take you to the edge.",
        "genres": ["Drama", "Music"],
        "language": "en",
        "release_date": "2014-10-10",
        "year": 2014,
        "runtime": 107,
        "poster_url": "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/vNXGrknvLCS7O3mXGvJ4XvM0b91.jpg",
        "trailer_key": "7d_jQycdQGo",
        "tmdb_rating": 8.4,
        "tmdb_votes": 14200,
        "popularity_score": 79.4,
        "director": "Damien Chazelle",
        "cast_members": ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
        "cinema_region": "hollywood",
        "keywords": ["jazz", "drummer", "obsession", "mentor", "perfection"],
        "editorial_collections": ["top_rated", "intense", "thoughtful"]
    },

    # ── Korean Cinema (Hallyu New Wave) ────────────────────────────────────
    {
        "tmdb_id": 496243,
        "imdb_id": "tt6751668",
        "title": "Parasite",
        "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
        "tagline": "Act like you own the place.",
        "genres": ["Comedy", "Thriller", "Drama"],
        "language": "ko",
        "release_date": "2019-05-30",
        "year": 2019,
        "runtime": 133,
        "poster_url": "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/hiKmpZMGZsrkA3cdEvAC2USckMT.jpg",
        "trailer_key": "5xH0Rqa1LTg",
        "tmdb_rating": 8.5,
        "tmdb_votes": 17800,
        "popularity_score": 92.5,
        "director": "Bong Joon Ho",
        "cast_members": ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik", "Park So-dam"],
        "cinema_region": "korean",
        "keywords": ["class conflict", "dark comedy", "seoul", "con artist", "basement"],
        "editorial_collections": ["trending", "top_rated", "thoughtful", "intense", "global_cinema_essentials"]
    },
    {
        "tmdb_id": 670,
        "imdb_id": "tt0364569",
        "title": "Oldboy",
        "overview": "Dear. After being kidnapped and imprisoned for fifteen years, Oh Dae-su is released, only to find that he must find his captor in five days.",
        "tagline": "15 years of imprisonment, 5 days of vengeance.",
        "genres": ["Drama", "Mystery", "Action", "Thriller"],
        "language": "ko",
        "release_date": "2003-11-21",
        "year": 2003,
        "runtime": 120,
        "poster_url": "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/l5V6k8Jb6kXU2V9k2g6vT6l6u7n.jpg",
        "trailer_key": "2HkjrJ6IK5E",
        "tmdb_rating": 8.3,
        "tmdb_votes": 8500,
        "popularity_score": 76.1,
        "director": "Park Chan-wook",
        "cast_members": ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jung", "Kim Byeong-ok"],
        "cinema_region": "korean",
        "keywords": ["revenge", "confinement", "mystery", "octopus", "twist"],
        "editorial_collections": ["top_rated", "intense", "scary"]
    },
    {
        "tmdb_id": 375022,
        "imdb_id": "tt4016934",
        "title": "The Handmaiden",
        "overview": "1930s Korea, in the period of Japanese occupation, a new girl is hired as a handmaiden to a Japanese heiress who lives a secluded life on a large countryside estate with her domineering uncle. But the maid has a secret: she is a pickpocket recruited by a swindler posing as a Japanese Count, who is trying to seduce the heiress, steal her fortune, and lock her in a madhouse.",
        "tagline": "Desire becomes a weapon.",
        "genres": ["Thriller", "Drama", "Romance"],
        "language": "ko",
        "release_date": "2016-06-01",
        "year": 2016,
        "runtime": 145,
        "poster_url": "https://image.tmdb.org/t/p/w500/8mncSnEbL3SVHXT5k2189j9kLsq.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/5n37E8P9kLskP1X5sDqL7KskW2q.jpg",
        "trailer_key": "whldChqCsYk",
        "tmdb_rating": 8.3,
        "tmdb_votes": 3600,
        "popularity_score": 68.4,
        "director": "Park Chan-wook",
        "cast_members": ["Kim Min-hee", "Kim Tae-ri", "Ha Jung-woo", "Cho Jin-woong"],
        "cinema_region": "korean",
        "keywords": ["heist", "erotic thriller", "period drama", "conspiracy", "lgbt"],
        "editorial_collections": ["top_rated", "romantic", "intense", "hidden_gems"]
    },
    {
        "tmdb_id": 11423,
        "imdb_id": "tt0353969",
        "title": "Memories of Murder",
        "overview": "In 1986, in the province of Gyunggi, in South Korea, a second young and beautiful woman is found dead, raped and tied and gagged with her underwear. Two local detectives, Park Doo-man and Cho Yong-koo, unaccustomed with such a heinous crime, investigate using crude methods.",
        "tagline": "The true story of a hunt for a serial killer.",
        "genres": ["Crime", "Drama", "Thriller"],
        "language": "ko",
        "release_date": "2003-05-02",
        "year": 2003,
        "runtime": 132,
        "poster_url": "https://image.tmdb.org/t/p/w500/2Yfg67YpX289ZgL9M96q4L5rW0u.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "dTnyhlyddLo",
        "tmdb_rating": 8.1,
        "tmdb_votes": 3800,
        "popularity_score": 62.0,
        "director": "Bong Joon Ho",
        "cast_members": ["Song Kang-ho", "Kim Sang-kyung", "Kim Roi-ha", "Song Jae-ho"],
        "cinema_region": "korean",
        "keywords": ["serial killer", "detective", "police procedural", "investigation", "rain"],
        "editorial_collections": ["top_rated", "intense", "thoughtful"]
    },

    # ── Japanese Cinema & Anime ────────────────────────────────────────────
    {
        "tmdb_id": 129,
        "imdb_id": "tt0245429",
        "title": "Spirited Away",
        "overview": "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
        "tagline": "The tunnel led to a mysterious world.",
        "genres": ["Animation", "Family", "Fantasy"],
        "language": "ja",
        "release_date": "2001-07-20",
        "year": 2001,
        "runtime": 125,
        "poster_url": "https://image.tmdb.org/t/p/w500/393WhBiiAIGJwJJmPqEGQWieshg.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg",
        "trailer_key": "ByXuk9QqQkk",
        "tmdb_rating": 8.5,
        "tmdb_votes": 15800,
        "popularity_score": 88.0,
        "director": "Hayao Miyazaki",
        "cast_members": ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki", "Takashi Naito"],
        "cinema_region": "japanese",
        "keywords": ["studio ghibli", "spirit world", "bathhouse", "dragon", "magic"],
        "editorial_collections": ["trending", "top_rated", "chill", "epic", "global_cinema_essentials", "anime"]
    },
    {
        "tmdb_id": 372058,
        "imdb_id": "tt5311514",
        "title": "Your Name.",
        "overview": "High schoolers Mitsuha and Taki are complete strangers living separate lives in different parts of Japan. But one night, they suddenly switch places. Mitsuha wakes up in Taki's body, and he in hers.",
        "tagline": "Treasure the experience. Dreams fade away after you wake up.",
        "genres": ["Animation", "Romance", "Drama"],
        "language": "ja",
        "release_date": "2016-08-26",
        "year": 2016,
        "runtime": 106,
        "poster_url": "https://image.tmdb.org/t/p/w500/q719qXXEzOoYaps6qFsxWa93bu.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "xU47nhruN-Q",
        "tmdb_rating": 8.5,
        "tmdb_votes": 11000,
        "popularity_score": 85.0,
        "director": "Makoto Shinkai",
        "cast_members": ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita", "Aoi Yuki"],
        "cinema_region": "japanese",
        "keywords": ["body swap", "comet", "time warp", "tokyo", "destiny"],
        "editorial_collections": ["top_rated", "romantic", "chill", "anime"]
    },
    {
        "tmdb_id": 346,
        "imdb_id": "tt0047478",
        "title": "Seven Samurai",
        "overview": "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
        "tagline": "The Mighty Seven Ride to Glory!",
        "genres": ["Action", "Drama"],
        "language": "ja",
        "release_date": "1954-04-26",
        "year": 1954,
        "runtime": 207,
        "poster_url": "https://image.tmdb.org/t/p/w500/8OKm79FR4FDZq7m2Jgswi4bX8bY.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/644g7hV4T7gZl5kU2xY6sM1V1eP.jpg",
        "trailer_key": "bBfgNp8q_m4",
        "tmdb_rating": 8.5,
        "tmdb_votes": 3500,
        "popularity_score": 64.0,
        "director": "Akira Kurosawa",
        "cast_members": ["Toshiro Mifune", "Takashi Shimura", "Keiko Tsushima", "Yukiko Shimazaki"],
        "cinema_region": "japanese",
        "keywords": ["samurai", "feudal japan", "village", "honor", "masterpiece"],
        "editorial_collections": ["top_rated", "epic", "thoughtful"]
    },
    {
        "tmdb_id": 491418,
        "imdb_id": "tt8075192",
        "title": "Shoplifters",
        "overview": "A family of small-time crooks take in a child they find on the freezing streets.",
        "tagline": "They stole what they needed. And found what they wanted.",
        "genres": ["Drama", "Crime"],
        "language": "ja",
        "release_date": "2018-06-08",
        "year": 2018,
        "runtime": 121,
        "poster_url": "https://image.tmdb.org/t/p/w500/wzV3wK6eC3bZ71L1j610S6iUj3o.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/a9e7M4Q7XpL5sD78qJ7m3bT2v4k.jpg",
        "trailer_key": "9382029",
        "tmdb_rating": 8.0,
        "tmdb_votes": 1700,
        "popularity_score": 52.0,
        "director": "Hirokazu Kore-eda",
        "cast_members": ["Lily Franky", "Sakura Ando", "Mayu Matsuoka", "Kairi Jyo"],
        "cinema_region": "japanese",
        "keywords": ["chosen family", "poverty", "palme d'or", "tokyo", "humanism"],
        "editorial_collections": ["thoughtful", "chill", "hidden_gems"]
    },

    # ── Indian Cinema (Bollywood, Tollywood, Kollywood, Malayalam) ─────────
    {
        "tmdb_id": 579974,
        "imdb_id": "tt8178634",
        "title": "RRR",
        "overview": "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
        "tagline": "Rise. Roar. Revolt.",
        "genres": ["Action", "Drama"],
        "language": "te",
        "release_date": "2022-03-24",
        "year": 2022,
        "runtime": 182,
        "poster_url": "https://image.tmdb.org/t/p/w500/wE0q2oxi0w7539CqM9O9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "GY4BgdUSpbE",
        "tmdb_rating": 8.1,
        "tmdb_votes": 6100,
        "popularity_score": 87.0,
        "director": "S. S. Rajamouli",
        "cast_members": ["N. T. Rama Rao Jr.", "Ram Charan", "Ajay Devgn", "Alia Bhatt", "Shriya Saran"],
        "cinema_region": "tollywood",
        "keywords": ["brotherhood", "colonial india", "spectacle", "pan-india", "action epic"],
        "editorial_collections": ["trending", "epic", "intense", "indian", "tollywood"]
    },
    {
        "tmdb_id": 20453,
        "imdb_id": "tt1187043",
        "title": "3 Idiots",
        "overview": "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them 'idiots'.",
        "tagline": "Don't chase success, chase excellence.",
        "genres": ["Comedy", "Drama"],
        "language": "hi",
        "release_date": "2009-12-23",
        "year": 2009,
        "runtime": 170,
        "poster_url": "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8swq.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/bT32R614nQ7M474vP61V6kU2v8b.jpg",
        "trailer_key": "K0eDlFX9GMc",
        "tmdb_rating": 8.0,
        "tmdb_votes": 3400,
        "popularity_score": 75.0,
        "director": "Rajkumar Hirani",
        "cast_members": ["Aamir Khan", "R. Madhavan", "Sharman Joshi", "Kareena Kapoor Khan", "Boman Irani"],
        "cinema_region": "bollywood",
        "keywords": ["engineering college", "friendship", "education system", "inspiration", "humor"],
        "editorial_collections": ["funny", "chill", "thoughtful", "indian", "bollywood"]
    },
    {
        "tmdb_id": 256040,
        "imdb_id": "tt2631186",
        "title": "Baahubali: The Beginning",
        "overview": "In ancient India, an adventurous and daring man becomes involved in a decadelong feud between two warring peoples.",
        "tagline": "The beginning of a legend.",
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "language": "te",
        "release_date": "2015-07-10",
        "year": 2015,
        "runtime": 159,
        "poster_url": "https://image.tmdb.org/t/p/w500/9BAjt85foFc9LWRdwR5dQ3s7yqa.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/vL581Zq5sD78qJ7m3bT2v4k8.jpg",
        "trailer_key": "sOEg_ynzGkc",
        "tmdb_rating": 7.7,
        "tmdb_votes": 2800,
        "popularity_score": 70.0,
        "director": "S. S. Rajamouli",
        "cast_members": ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia", "Ramya Krishnan"],
        "cinema_region": "tollywood",
        "keywords": ["kingdom", "war", "epic fantasy", "waterfall", "royalty"],
        "editorial_collections": ["epic", "intense", "indian", "tollywood"]
    },
    {
        "tmdb_id": 843241,
        "imdb_id": "tt9179430",
        "title": "Vikram",
        "overview": "A special agent investigates a murder committed by a masked group of serial killers. However, a tangled maze of clues soon leads him to the drug kingpin of Chennai.",
        "tagline": "Once upon a time there lived a ghost...",
        "genres": ["Action", "Thriller", "Crime"],
        "language": "ta",
        "release_date": "2022-06-03",
        "year": 2022,
        "runtime": 174,
        "poster_url": "https://image.tmdb.org/t/p/w500/bJypv3Zk1m7W8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "OKBMCL-frPU",
        "tmdb_rating": 8.2,
        "tmdb_votes": 2300,
        "popularity_score": 68.0,
        "director": "Lokesh Kanagaraj",
        "cast_members": ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Suriya"],
        "cinema_region": "tamil",
        "keywords": ["lcu", "drug cartel", "undercover", "high octane", "guns"],
        "editorial_collections": ["intense", "epic", "indian", "tamil", "kollywood"]
    },
    {
        "tmdb_id": 194662,
        "imdb_id": "tt2350496",
        "title": "The Lunchbox",
        "overview": "A mistaken delivery in Mumbai's famously efficient lunchbox delivery system connects a young housewife to an older man in the dusk of his life as they build a fantasy world together through notes in the lunchbox.",
        "tagline": "Sometimes the wrong train takes you to the right station.",
        "genres": ["Drama", "Romance"],
        "language": "hi",
        "release_date": "2013-09-20",
        "year": 2013,
        "runtime": 104,
        "poster_url": "https://image.tmdb.org/t/p/w500/77wF237kL8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/vL581Zq5sD78qJ7m3bT2v4k8.jpg",
        "trailer_key": "IJ_2QKcE13A",
        "tmdb_rating": 7.9,
        "tmdb_votes": 1900,
        "popularity_score": 58.0,
        "director": "Ritesh Batra",
        "cast_members": ["Irrfan Khan", "Nimrat Kaur", "Nawazuddin Siddiqui", "Lillete Dubey"],
        "cinema_region": "bollywood",
        "keywords": ["dabbawala", "mumbai", "letters", "cooking", "loneliness"],
        "editorial_collections": ["romantic", "chill", "thoughtful", "indian", "hidden_gems"]
    },

    # ── French Cinema (Nouvelle Vague & Modern Art-House) ─────────────────
    {
        "tmdb_id": 194,
        "imdb_id": "tt0211915",
        "title": "Amélie",
        "overview": "Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.",
        "tagline": "She'll change your life.",
        "genres": ["Comedy", "Romance"],
        "language": "fr",
        "release_date": "2001-04-25",
        "year": 2001,
        "runtime": 122,
        "poster_url": "https://image.tmdb.org/t/p/w500/bVpvf2l932M7W8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "HUECWi5pX7o",
        "tmdb_rating": 8.0,
        "tmdb_votes": 12000,
        "popularity_score": 78.0,
        "director": "Jean-Pierre Jeunet",
        "cast_members": ["Audrey Tautou", "Mathieu Kassovitz", "Rufus", "Lorella Cravotta"],
        "cinema_region": "french",
        "keywords": ["paris", "montmartre", "whimsical", "imagination", "kindness"],
        "editorial_collections": ["romantic", "funny", "chill", "french"]
    },
    {
        "tmdb_id": 531428,
        "imdb_id": "tt8613070",
        "title": "Portrait of a Lady on Fire",
        "overview": "On an isolated island in Brittany at the end of the eighteenth century, a female painter is commissioned to paint a wedding portrait of a young woman.",
        "tagline": "Do not regret. Remember.",
        "genres": ["Drama", "Romance", "History"],
        "language": "fr",
        "release_date": "2019-09-18",
        "year": 2019,
        "runtime": 122,
        "poster_url": "https://image.tmdb.org/t/p/w500/3A8k67Z89qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "R-fQPT4xm7k",
        "tmdb_rating": 8.2,
        "tmdb_votes": 3100,
        "popularity_score": 65.0,
        "director": "Céline Sciamma",
        "cast_members": ["Noémie Merlant", "Adèle Haenel", "Luàna Bajrami", "Valeria Golino"],
        "cinema_region": "french",
        "keywords": ["painting", "brittany", "gaze", "queer romance", "art"],
        "editorial_collections": ["thoughtful", "romantic", "french", "hidden_gems"]
    },
    {
        "tmdb_id": 77338,
        "imdb_id": "tt1675434",
        "title": "The Intouchables",
        "overview": "A true story of two men who should never have met – a quadriplegic aristocrat who was injured in a paragliding accident and a young man from the projects who becomes his caregiver.",
        "tagline": "Sometimes you have to reach into someone else's world to find out what's missing in your own.",
        "genres": ["Drama", "Comedy"],
        "language": "fr",
        "release_date": "2011-11-02",
        "year": 2011,
        "runtime": 112,
        "poster_url": "https://image.tmdb.org/t/p/w500/1QUB22q932M7W8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "34WIbmXkewU",
        "tmdb_rating": 8.3,
        "tmdb_votes": 17000,
        "popularity_score": 79.0,
        "director": "Olivier Nakache",
        "cast_members": ["François Cluzet", "Omar Sy", "Anne Le Ny", "Audrey Fleurot"],
        "cinema_region": "french",
        "keywords": ["friendship", "caregiver", "aristocrat", "wheelchair", "humor"],
        "editorial_collections": ["funny", "chill", "thoughtful", "french"]
    },

    # ── Spanish & Latin American Cinema ────────────────────────────────────
    {
        "tmdb_id": 1417,
        "imdb_id": "tt0457430",
        "title": "Pan's Labyrinth",
        "overview": "In the Falangist Spain of 1944, the bookish young stepdaughter of a sadistic army officer escapes into an eerie but captivating fantasy world.",
        "tagline": "Innocence has a power evil cannot imagine.",
        "genres": ["Drama", "Fantasy", "War"],
        "language": "es",
        "release_date": "2006-08-25",
        "year": 2006,
        "runtime": 118,
        "poster_url": "https://image.tmdb.org/t/p/w500/77wF237kL8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "EqYiSlkvRuw",
        "tmdb_rating": 8.0,
        "tmdb_votes": 10500,
        "popularity_score": 74.0,
        "director": "Guillermo del Toro",
        "cast_members": ["Ivana Baquero", "Sergi López", "Maribel Verdú", "Doug Jones"],
        "cinema_region": "spanish",
        "keywords": ["faun", "fairy tale", "spanish civil war", "creature", "dark fantasy"],
        "editorial_collections": ["intense", "scary", "epic", "spanish"]
    },
    {
        "tmdb_id": 426426,
        "imdb_id": "tt6155172",
        "title": "Roma",
        "overview": "In 1970s Mexico City, two domestic workers help a mother of four while her husband is away for an extended period of time.",
        "tagline": "Memory connects what reality separates.",
        "genres": ["Drama"],
        "language": "es",
        "release_date": "2018-11-21",
        "year": 2018,
        "runtime": 135,
        "poster_url": "https://image.tmdb.org/t/p/w500/dtILh8Z7W8qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7k2m968Z9YqL098k7m4N1v78gYv.jpg",
        "trailer_key": "6BS27ngZtxg",
        "tmdb_rating": 7.8,
        "tmdb_votes": 4200,
        "popularity_score": 55.0,
        "director": "Alfonso Cuarón",
        "cast_members": ["Yalitza Aparicio", "Marina de Tavira", "Diego Cortina Autrey", "Carlos Peralta"],
        "cinema_region": "spanish",
        "keywords": ["mexico city", "black and white", "domestic worker", "autobiographical", "family"],
        "editorial_collections": ["thoughtful", "chill", "spanish", "hidden_gems"]
    },

    # ── Iranian Cinema (Humanist Realism) ──────────────────────────────────
    {
        "tmdb_id": 62206,
        "imdb_id": "tt1832382",
        "title": "A Separation",
        "overview": "A married couple is faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer's disease.",
        "tagline": "Love, Honor, Pride, Deceit.",
        "genres": ["Drama"],
        "language": "fa",
        "release_date": "2011-03-16",
        "year": 2011,
        "runtime": 123,
        "poster_url": "https://image.tmdb.org/t/p/w500/8MNf189qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "B2Sswx_MUWw",
        "tmdb_rating": 8.0,
        "tmdb_votes": 2400,
        "popularity_score": 50.0,
        "director": "Asghar Farhadi",
        "cast_members": ["Peyman Moaadi", "Leila Hatami", "Sareh Bayat", "Shahab Hosseini"],
        "cinema_region": "iranian",
        "keywords": ["tehran", "divorce", "moral dilemma", "alzheimer", "courtroom"],
        "editorial_collections": ["thoughtful", "intense", "iranian", "hidden_gems"]
    },
    {
        "tmdb_id": 16459,
        "imdb_id": "tt0118849",
        "title": "Children of Heaven",
        "overview": "After a boy loses his sister's pair of shoes, he goes on a series of adventures in order to find them. When he is unsuccessful, he tries a new way to win a new pair.",
        "tagline": "A story about love, courage and a pair of pink shoes.",
        "genres": ["Drama", "Family"],
        "language": "fa",
        "release_date": "1997-02-01",
        "year": 1997,
        "runtime": 89,
        "poster_url": "https://image.tmdb.org/t/p/w500/987Yy6Z89qL4kM8o9jE84p5B.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "8_vYwK71mN8",
        "tmdb_rating": 8.1,
        "tmdb_votes": 1200,
        "popularity_score": 45.0,
        "director": "Majid Majidi",
        "cast_members": ["Mohammad Amir Naji", "Amir Farrokh Hashemian", "Bahare Seddiqi"],
        "cinema_region": "iranian",
        "keywords": ["shoes", "race", "siblings", "poverty", "innocence"],
        "editorial_collections": ["thoughtful", "chill", "iranian", "hidden_gems"]
    }
]
